# start with docker-compose -f modular.yml up -d

version: '3'

services:

  leaderboard:
    container_name: leaderboard
    image: "leaderboard_img"

    ports:
      - "26656:26657"
      - "1316:1317"
      - "4499:4500"

    networks:
      - checkersdemo

  checkers:
    container_name: checkers
    image: "checkers_img"

    ports:
      - "26657:26657"
      - "1317:1317"
      - "4500:4500"

    networks:
      - checkersdemo

  relayer:
    container_name: relayer
    image: "relayer_img"
    tty: true
    stdin_open: true

    networks:
      - checkersdemo

networks:
    checkersdemo: